const IMAGE_URL = '../assets/images/';
/**
 * @param {number} id - The customer ID
 * @param {string} title - The customer title
 * @param {string} description - The customer description
 * @param {string} imageURL - The URL of the customer image
 * @param {string} url - The customer URL
 * @param {string} label - The customer label
 */

export const customersItem = [
  {
    id: 1,
    title: 'Antalis - E-commerce | 2023',
    description: `<li>Développement des sliders produits,</li><li>Système atomic design</li><li>HTML | CSS | JavaScript / jQuery</li>Bootstrap<li></li>`,
    imageURL: IMAGE_URL + 'antalis.webp',
    url: 'https://www.antalis.fr',
    label: 'Antalis',
  },
  {
    id: 2,
    title: 'France TV - Audiovisuel | 2022',
    description: `<li>Développement du player direct-radio</li><li>Mise en place de l'accessibilité</li><li>Optimisation de la performance</li><li>Twig | CSS / Sass | JavaScript</li>`,
    imageURL: IMAGE_URL + 'francetv.webp',
    url: 'https://la1ere.francetvinfo.fr/direct-radio/',
    label: 'France TV, la 1ere',
  },
  {
    id: 3,
    title: 'Action contre la faim | 2021',
    description: `<li>Développement de la modale cookies</li><li>Responsive</li><li>HTML | CSS / Sass | JavaScript </li>`,
    imageURL: IMAGE_URL + 'actioncontrelafaim.webp',
    url: 'https://www.actioncontrelafaim.org/',
    label: 'Action contre la faim',
  },
  {
    id: 4,
    title: 'Christian Louboutin - luxe | 2019',
    description: `<li>Développement de la FAQ</li><li>Intégration de templates pour Emails transactionnels</li><li>HTML | CSS | jQuery </li>`,
    imageURL: IMAGE_URL + 'louboutin.webp',
    url: 'https://eu.christianlouboutin.com/fr_fr/',
    label: 'Christian Louboutin',
  },
  {
    id: 5,
    title: 'Louis Vuitton - luxe | 2018 - 2019',
    description: `<li>Site carrière LVMH from scratch</li><li>Mise en place de l'accessibilité</li><li>HTML | CSS / Less | jQuery</li>`,
    imageURL: IMAGE_URL + 'louisvuitton.webp',
    url: 'https://fr.louisvuitton.com/fra-fr/homepage',
    label: 'Louis Vuitton',
  },
  {
    id: 6,
    title: 'Angelus Plongée | 2020',
    description: `<li>WordPress, template vierge</li><li>Optimisation de la performance</li><li>Aspect UI / UX</li><li>S.E.O naturel</li><li>HTML | CSS | jQuery | Bootstrap</li>`,
    imageURL: IMAGE_URL + 'angelusplongee.webp',
    url: 'https://angelus-plongee.com/',
    label: 'Angelus Plongée',
  },
  {
    id: 7,
    title: "J'Irai marcher sur les Toits | 2020",
    description: `<li>WordPress, template vierge</li><li>Optimisation de la performance</li><li>Aspect UI / UX</li><li>S.E.O naturel</li><li>HTML | CSS | jQuery | Bootstrap</li>`,
    imageURL: IMAGE_URL + 'jirai.webp',
    url: 'https://jirai.fr/',
    label: "J'Irai marcher sur les Toits",
  },
  {
    id: 8,
    title: 'OTAA Architecture | 2017',
    description: `<li>WordPress, template vierge</li><li> HTML | CSS | jQuery</li>`,
    imageURL: IMAGE_URL + 'otaa.webp',
    url: 'https://www.otaa.fr/',
    label: 'OTAA architecture',
  },
  {
    id: 9,
    title: 'Crédey & Associés | 2016',
    description: `<li>WordPress, template vierge</li><li>HTML | CSS | jQuery</li>`,
    imageURL: IMAGE_URL + 'credey.webp',
    url: 'https://credey.com/fr/accueil/',
    label: 'Crédey & Associés',
  },
  {
    id: 10,
    title: 'Dotline - Informatique | 2016',
    description: `<li>WordPress, template vierge</li><li>HTML | CSS | jQuery</li>`,
    imageURL: IMAGE_URL + 'dotline.webp',
    url: 'https://www.dotline.fr/',
    label: 'Dotline - Informatique',
  },
  {
    id: 11,
    title: 'Sodexo - Restauration | 2016',
    description: `<li>Migration du site vers le CMS Jahia</li><li>Intégration du contenu</li>`,
    imageURL: IMAGE_URL + 'sodexo.webp',
    url: 'https://fr.sodexo.com/home.html',
    label: 'Sodexo',
  },
  {
    id: 12,
    title: 'Bouyges Telecom | 2012',
    description: `<li>Publicité marketing</li><li>Développement Flash</li><li>HTML | CSS | ActionScript</li>`,
    imageURL: IMAGE_URL + 'bouyguestelecom.webp',
    url: 'https://www.bouyguestelecom.fr/',
    label: 'Bouyges Telecom',
  },
  {
    id: 13,
    title: 'Société Générale | 2011',
    description: `<li>Application board traders</li><li>Développement Flash</li><li>HTML | CSS | ActionScript</li>`,
    imageURL: IMAGE_URL + 'societegenerale.webp',
    url: 'https://www.societegenerale.com/fr',
    label: 'Société Générale',
  },
  {
    id: 14,
    title: 'Fondation Mallet | 2010',
    description: `<li>Développement WordPress</li><li>HTML | CSS | Php</li>`,
    imageURL: IMAGE_URL + 'fondationmallet.webp',
    url: 'https://www.fondationmallet.fr/',
    label: 'Fondation Mallet',
  },
  {
    id: 15,
    title: 'Raoul Follereau | 2010',
    description: `<li>Développement WordPress</li><li>HTML | CSS | Php</li>`,
    imageURL: IMAGE_URL + 'raoulfollereau.webp',
    url: 'https://www.raoul-follereau.org/',
    label: 'Raoul Follereau',
  },
  {
    id: 16,
    title: 'DNDi | 2009',
    description: `<li>Développement WordPress</li><li>HTML | CSS</li>`,
    imageURL: IMAGE_URL + 'dndi.webp',
    url: 'https://dndi.org/',
    label: 'DNDi',
  },
  {
    id: 17,
    title: 'Lagardère - Presse | 2009',
    description: `<li>Développement Intranet du livre blanc</li><li>HTML | CSS | Php</li>`,
    imageURL: IMAGE_URL + 'lagardere.webp',
    url: 'https://www.lagardere.com/',
    label: 'Lagardère',
  },
  {
    id: 18,
    title: 'BNP Paribas - Banque | 2008',
    description: `<li>Intégration landing page</li><li>HTML | CSS</li>`,
    imageURL: IMAGE_URL + 'bnpparibas.webp',
    url: 'https://mabanque.bnpparibas/',
    label: 'BNP Paribas',
  },
  {
    id: 19,
    title: 'BNP Paribas - Banque | 2008',
    description: `<li>Intégration landing page</li><li>HTML | CSS</li>`,
    imageURL: IMAGE_URL + 'canalplus.webp',
    url: 'https://www.canalplus.com/',
    label: 'Canal +',
  },
];
