export const customersItem = [
  {
    id: 1,
    title: 'Antalis - E-commerce | 2023',
    description: `<li>Développement des sliders produits,</li><li>Système atomic design</li><li>HTML | CSS | JavaScript / jQuery | Bootstrap </li>`,
    imageURL: '../assets/images/antalis.webp',
    url: 'https://www.antalis.fr',
    caption: 'Antalis',
    ariaLabel: 'Antalis',
    alt: 'Vignette Antalis',
  },
  {
    id: 2,
    title: 'France TV - Audiovisuel | 2022',
    description: `<li>Développement du player direct-radio</li><li>Mise en place de l'accessibilité</li><li>Optimisation de la performance</li><li>Twig | CSS / Sass | JavaScript</li>`,
    imageURL: '../assets/images/francetv.webp',
    url: 'https://la1ere.francetvinfo.fr/direct-radio/',
    caption: 'France TV, la 1ere',
    ariaLabel: 'France TV, la 1ere',
    alt: 'Vignette France TV, la 1ere',
  },
  {
    id: 3,
    title: 'Action contre la faim | 2021',
    description: `<li>Développement de la modale cookies</li><li>Responsive</li><li>HTML | CSS / Sass | JavaScript </li>`,
    imageURL: '../assets/images/actioncontrelafaim.webp',
    url: 'https://www.actioncontrelafaim.org/',
    caption: 'Action contre la faim',
    ariaLabel: 'Action contre la faim',
    alt: 'Vignette Action contre la faim',
  },
  {
    id: 4,
    title: 'Christian Louboutin | 2019',
    description: `<li>Développement de la FAQ</li><li>Intégration de templates pour Emails transactionnels</li><li>HTML | CSS | jQuery </li>`,
    imageURL: '../assets/images/louboutin.webp',
    url: 'https://eu.christianlouboutin.com/fr_fr/',
    caption: 'Christian Louboutin',
    ariaLabel: 'Christian Louboutin',
    alt: 'Vignette Christian Louboutin',
  },
  {
    id: 5,
    title: 'Louis Vuitton - Luxe | 2018 - 2019',
    description: `<li>Site carrière LVMH from scratch</li><li>Mise en place de l'accessibilité</li><li>HTML | CSS / Less | jQuery</li>`,
    imageURL: '../assets/images/louisvuitton.webp',
    url: 'https://fr.louisvuitton.com/fra-fr/homepage',
    caption: 'Louis Vuitton',
    ariaLabel: 'Louis Vuitton',
    alt: 'Vignette Louis Vuitton',
  },
];
