export const customersItem = [
  {
    id: 1,
    title: 'Antalis - E-commerce | 2023',
    description: `<li>Développement des sliders produits,</li><li>Système atomic design</li><li>HTML | CSS | JavaScript / jQuery | Bootstrap </li>`,
    imageURL: '../assets/images/antalis.webp',
    url: 'https://www.antalis.fr',
    caption: 'Antalis',
    ariaLabel: 'Antalis',
    alt: 'Vignette Antalis',
  },
  {
    id: 2,
    title: 'France TV - Audiovisuel | 2022',
    description: `<li>Développement du player direct-radio</li><li>Mise en place de l'accessibilité</li><li>Optimisation de la performance</li><li>Twig | CSS / Sass | JavaScript</li>`,
    imageURL: '../assets/images/francetv.webp',
    url: 'https://la1ere.francetvinfo.fr/direct-radio/',
    caption: 'France TV, la 1ere',
    ariaLabel: 'France TV, la 1ere',
    alt: 'Vignette France TV, la 1ere',
  },
  {
    id: 3,
    title: 'Action contre la faim | 2021',
    description: `<li>Développement de la modale cookies</li><li>Responsive</li><li>HTML | CSS / Sass | JavaScript </li>`,
    imageURL: '../assets/images/actioncontrelafaim.webp',
    url: 'https://www.actioncontrelafaim.org/',
    caption: 'Action contre la faim',
    ariaLabel: 'Action contre la faim',
    alt: 'Vignette Action contre la faim',
  },
  {
    id: 4,
    title: 'Christian Louboutin | 2019',
    description: `<li>Développement de la FAQ</li><li>Intégration de templates pour Emails transactionnels</li><li>HTML | CSS | jQuery </li>`,
    imageURL: '../assets/images/louboutin.webp',
    url: 'https://eu.christianlouboutin.com/fr_fr/',
    caption: 'Christian Louboutin',
    ariaLabel: 'Christian Louboutin',
    alt: 'Vignette Christian Louboutin',
  },
  {
    id: 5,
    title: 'Louis Vuitton - Luxe | 2018 - 2019',
    description: `<li>Site carrière LVMH from scratch</li><li>Mise en place de l'accessibilité</li><li>HTML | CSS / Less | jQuery</li>`,
    imageURL: '../assets/images/louisvuitton.webp',
    url: 'https://fr.louisvuitton.com/fra-fr/homepage',
    caption: 'Louis Vuitton',
    ariaLabel: 'Louis Vuitton',
    alt: 'Vignette Louis Vuitton',
  },
  {
    id: 6,
    title: 'Angelus Plongée | 2020',
    description: `<li>WordPress, template vierge</li><li>Optimisation de la performance</li><li>Aspect UI / UX</li><li>S.E.O naturel</li><li>HTML | CSS | jQuery | Bootstrap</li>`,
    imageURL: '../assets/images/angelusplongee.webp',
    url: 'https://angelus-plongee.com/',
    caption: 'Angelus Plongée',
    ariaLabel: 'Angelus Plongée',
    alt: 'Vignette Angelus Plongée',
  },
  {
    id: 7,
    title: "J'Irai marcher sur les Toits | 2020",
    description: `<li>WordPress, template vierge</li><li>Optimisation de la performance</li><li>Aspect UI / UX</li><li>S.E.O naturel</li><li>HTML | CSS | jQuery | Bootstrap</li>`,
    imageURL: '../assets/images/jirai.webp',
    url: 'https://jirai.fr/',
    caption: "J'Irai marcher sur les Toits",
    ariaLabel: "J'Irai marcher sur les Toits",
    alt: "Vignette J'Irai marcher sur les Toits",
  },
  {
    id: 8,
    title: 'OTAA Architecture | 2017',
    description: `<li>WordPress, template vierge</li><li> HTML | CSS | jQuery</li>`,
    imageURL: '../assets/images/otaa.webp',
    url: 'https://www.otaa.fr/',
    caption: 'OTAA architecture',
    ariaLabel: 'OTAA architecture',
    alt: 'Vignette OTAA architecture',
  },
  {
    id: 9,
    title: 'Crédey & Associés | 2016',
    description: `<li>WordPress, template vierge</li><li>HTML | CSS | jQuery</li>`,
    imageURL: '../assets/images/credey.webp',
    url: 'https://credey.com/fr/accueil/',
    caption: 'Crédey & Associés',
    ariaLabel: 'Crédey & Associés',
    alt: 'Vignette Crédey & Associés',
  },
  {
    id: 10,
    title: 'Dotline - Informatique | 2016',
    description: `<li>WordPress, template vierge</li><li>HTML | CSS | jQuery</li>`,
    imageURL: '../assets/images/dotline.webp',
    url: 'https://www.dotline.fr/',
    caption: 'Dotline - Informatique',
    ariaLabel: 'Dotline - Informatique',
    alt: 'Vignette Dotline - Informatique',
  },
  {
    id: 11,
    title: 'Sodexo - Restauration | 2016',
    description: `<li>Migration du site vers le CMS Jahia</li><li>Intégration du contenu</li>`,
    imageURL: '../assets/images/sodexo.webp',
    url: 'https://fr.sodexo.com/home.html',
    caption: 'Sodexo',
    ariaLabel: 'Sodexo',
    alt: 'Vignette Sodexo',
  },
  {
    id: 12,
    title: 'Bouyges Telecom | 2012',
    description: `<li>Publicité marketing</li><li>Développement Flash</li><li>HTML | CSS | ActionScript</li>`,
    imageURL: '../assets/images/bouyguestelecom.webp',
    url: 'https://www.bouyguestelecom.fr/',
    caption: 'Bouyges Telecom',
    ariaLabel: 'Bouyges Telecom',
    alt: 'Vignette Bouyges Telecom',
  },
  {
    id: 13,
    title: 'Société Générale | 2011',
    description: `<li>Application board traders</li><li>Développement Flash</li><li>HTML | CSS | ActionScript</li>`,
    imageURL: '../assets/images/societegenerale.webp',
    url: 'https://www.societegenerale.com/fr',
    caption: 'Société Générale',
    ariaLabel: 'Société Générale',
    alt: 'Vignette Société Générale',
  },
  {
    id: 14,
    title: 'Fondation Mallet | 2010',
    description: `<li>Développement WordPress</li><li>HTML | CSS | Php</li>`,
    imageURL: '../assets/images/fondationmallet.webp',
    url: 'https://www.fondationmallet.fr/',
    caption: 'Fondation Mallet',
    ariaLabel: 'Fondation Mallet',
    alt: 'Vignette Fondation Mallet',
  },
  {
    id: 15,
    title: 'Raoul Follereau | 2010',
    description: `<li>Développement WordPress</li><li>HTML | CSS | Php</li>`,
    imageURL: '../assets/images/raoulfollereau.webp',
    url: 'https://www.raoul-follereau.org/',
    caption: 'Raoul Follereau',
    ariaLabel: 'Raoul Follereau',
    alt: 'Vignette Raoul Follereau',
  },
  {
    id: 16,
    title: 'DNDi | 2009',
    description: `<li>Développement WordPress</li><li>HTML | CSS</li>`,
    imageURL: '../assets/images/dndi.webp',
    url: 'https://dndi.org/',
    caption: 'DNDi',
    ariaLabel: 'DNDi',
    alt: 'Vignette DNDi',
  },
  {
    id: 17,
    title: 'Lagardère - Presse | 2009',
    description: `<li>Développement Intranet du livre blanc</li><li>HTML | CSS | Php</li>`,
    imageURL: '../assets/images/lagardere.webp',
    url: 'https://www.lagardere.com/',
    caption: 'Lagardère',
    ariaLabel: 'Lagardère',
    alt: 'Vignette Lagardère',
  },
  {
    id: 18,
    title: 'BNP Paribas - Banque | 2008',
    description: `<li>Intégration landing page</li><li>HTML | CSS</li>`,
    imageURL: '../assets/images/bnpparibas.webp',
    url: 'https://mabanque.bnpparibas/',
    caption: 'BNP Paribas',
    ariaLabel: 'BNP Paribas',
    alt: 'Vignette BNP Paribas',
  },
  {
    id: 19,
    title: 'BNP Paribas - Banque | 2008',
    description: `<li>Intégration landing page</li><li>HTML | CSS</li>`,
    imageURL: '../assets/images/canalplus.webp',
    url: 'https://www.canalplus.com/',
    caption: 'Canal +',
    ariaLabel: 'Canal +',
    alt: 'Vignette Canal +',
  },
];
